import assert from 'node:assert/strict';
import ts from 'typescript';
import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const js = ts.transpileModule(await readFile('lib/creator-profile.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const mod = { exports: {} }; new Function('module', 'exports', js)(mod, mod.exports);
const { creatorProfile } = mod.exports;
const instagram = { id: 'nadia-september', platform: 'Instagram', creator: 'Nadia · @abudhabi.finds', url: 'https://www.instagram.com/abudhabi.finds/p/Dd81ibgkZqE/' };
assert.equal(creatorProfile(instagram).url, 'https://www.instagram.com/abudhabi.finds/');
assert.notEqual(creatorProfile(instagram).url, instagram.url);
const tiktok = { id: 'tiktok-umut', platform: 'TikTok', creator: '@umutdxb', url: 'https://www.tiktok.com/@umutdxb/video/7450801276549565703' };
assert.equal(creatorProfile(tiktok).url, 'https://www.tiktok.com/@umutdxb');
const youtube = { id: 'food-week-grace', platform: 'YouTube', creator: 'Lottie Grace', url: 'https://www.youtube.com/watch?v=zodFLhLH9xE' };
assert.equal(creatorProfile(youtube).url, 'https://www.youtube.com/channel/UCBLM4f6isg9jLKW52uhpOHA');
assert.equal(creatorProfile({ ...youtube, id: 'unknown' }), null);
assert.equal(creatorProfile({ ...youtube, url: 'https://www.youtube.com/watch?v=unreviewed' }), null);
for (const url of ['http://www.instagram.com/abudhabi.finds/p/Dd81ibgkZqE/', 'https://www.instagram.com.evil.test/abudhabi.finds/p/Dd81ibgkZqE/', 'https://secret@www.instagram.com/abudhabi.finds/p/Dd81ibgkZqE/', 'https://www.instagram.com:8443/abudhabi.finds/p/Dd81ibgkZqE/', 'javascript:alert(1)', 'https://www.instagram.com/p/Dd81ibgkZqE/', 'https://www.instagram.com/another/p/Dd81ibgkZqE/', 'https://www.instagram.com/abudhabi.finds%22/p/Dd81ibgkZqE/']) assert.equal(creatorProfile({ ...instagram, url }), null);
assert.equal(creatorProfile({ ...tiktok, creator: '@another' }), null);
assert.equal(creatorProfile({ ...tiktok, url: 'https://www.tiktok.com/@umutdxb/video/7450801276549565703/extra' }), null);
assert.equal(creatorProfile({ ...instagram, platform: 'Official source' }), null);
const story = await readFile('components/story-viewer.tsx', 'utf8');
assert.ok(story.includes('</button><CreatorLink source={source}/>'));
assert.ok(story.includes('rel="noopener noreferrer"'));
assert.ok(story.includes('profile on ${source.platform} (new tab)'));
const require = createRequire(import.meta.url);
const storyJs = ts.transpileModule(story, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, jsx: ts.JsxEmit.ReactJSX } }).outputText;
const storyMod = { exports: {} };
new Function('require', 'module', 'exports', storyJs)((name) => name === '../lib/creator-profile' ? mod.exports : name.endsWith('.css') ? {} : require(name), storyMod, storyMod.exports);
const React = require('react');
const { renderToStaticMarkup } = require('react-dom/server');
const markup = renderToStaticMarkup(React.createElement(storyMod.exports.default, { sources: [instagram, tiktok, youtube, { ...youtube, id: 'unknown', creator: 'Another creator' }].map(source => ({ ...source, title: 'Original source' })), renderMedia: () => null, onExplore: () => {}, onSave: () => {}, isSaved: () => false }));
assert.equal((markup.match(/<a /g) ?? []).length, 3);
for (const body of markup.matchAll(/<button\b[^>]*>([\s\S]*?)<\/button>/g)) assert.ok(!body[1].includes('<a '), 'Profile links must not nest inside story opener buttons');
assert.ok(markup.includes('href="https://www.instagram.com/abudhabi.finds/"'));
assert.ok(markup.includes('Open Nadia · @abudhabi.finds profile on Instagram (new tab)'));
console.log('PASS creator profile targets, original/profile distinction, attributed handles, unsafe URLs, unknown YouTube channels and separate accessible controls');
