import { db,identity,protect,responseError,entity,HttpError,visible,isAdmin } from '@/lib/server';
import { kinds,validate,type Kind } from '@/lib/model';
import { reviewedContent } from '@/lib/review-content';
export async function POST(req:Request){try{protect(req);const u=await identity();const b:any=await req.json();if(!kinds.includes(b.kind))throw new HttpError(400,'Unknown workspace type');const kind=b.kind as Kind;if(kind==='source'&&!isAdmin(u.userId,u.email))throw new HttpError(403,'Moderator access required');const data=validate(kind,b.data);if(kind==='request'){(data as any).helperId='';(data as any).replies=[];}if(kind==='submission'&&(data as any).status!=='pending')throw new HttpError(400,'New submissions start pending');if(kind==='proof'){if((data as any).review==='reviewed')throw new HttpError(403,'New artifacts have no human review');(data as any).reviewer='';(data as any).reviewEvidence='';(data as any).reviewHash='';}if(kind==='request'&&!['draft','open'].includes((data as any).status))throw new HttpError(400,'New asks start draft or open');const id=['profile','helper'].includes(kind)?`${kind}:${u.userId}`:b.id;if(typeof id!=='string'||id.length>100)throw new HttpError(400,'Invalid ID');const now=new Date().toISOString();await db().prepare('INSERT OR IGNORE INTO entities(id,owner,kind,data,created,updated) VALUES(?,?,?,?,?,?)').bind(id,u.userId,kind,JSON.stringify(data),now,now).run();const row=await entity(id,u.userId);if(row.kind!==kind)throw new HttpError(409,'ID already used');return Response.json(visible(row,u.userId));}catch(e){return responseError(e);}}
export async function PATCH(req:Request){try{protect(req);const u=await identity();const b:any=await req.json();const row=await entity(b.id,u.userId,true);if(row.deleted&&b.op!=='restore')throw new HttpError(409,'Restore this item before editing');let data=row.data,deleted=row.deleted;
if(b.op==='trash'||b.op==='restore'){if(row.role!=='owner')throw new HttpError(403,'Only the owner can remove or restore');deleted=b.op==='trash'?1:0;}
else{data=validate(row.kind,b.data);if(row.owner!==u.userId){if(row.kind==='profile')throw new HttpError(403,'Profile is private');data={...data,privateNotes:row.data.privateNotes};}if(row.kind==='submission'&&!isAdmin(u.userId,u.email)&&!['pending','withdrawn','correction'].includes(data.status))throw new HttpError(403,'Moderator review required');
if(row.kind==='proof'){if(data.review==='reviewed'&&row.data.review!=='reviewed')throw new HttpError(403,'Use the collaborator review workflow');data.reviewer=row.data.reviewer;data.reviewEvidence=row.data.reviewEvidence;data.reviewHash=row.data.reviewHash??'';if(reviewedContent(data)!==reviewedContent(row.data)){data.review='not requested';data.reviewer='';data.reviewEvidence='';data.reviewHash='';}}
if(row.kind==='request'){data.helperId=row.data.helperId;data.replies=row.data.replies;data.history=row.data.history??[];const allowed:Record<string,string[]>={draft:['draft','open'],open:['open','draft'],accepted:['accepted'],answered:['answered','resolved'],resolved:['resolved','open']};if(!allowed[row.data.status]?.includes(data.status))throw new HttpError(409,'Use the request workflow');if(row.data.status==='resolved'&&data.status==='open'){data.history=[...data.history,{helperId:row.data.helperId,replies:row.data.replies,resolution:row.data.resolution,closedAt:new Date().toISOString()}];data.helperId='';data.replies=[];data.resolution='';data.feedback='';}}
}
const now=new Date().toISOString();const statements:D1PreparedStatement[]=[];
if(row.kind==='submission'&&(deleted||['withdrawn','correction'].includes(data.status))){statements.push(db().prepare("UPDATE entities SET data=json_set(data,'$.status',?),version=version+1,updated=? WHERE id=? AND EXISTS(SELECT 1 FROM entities WHERE id=? AND version=?)").bind(deleted||data.status==='withdrawn'?'withdrawn':'needs review',now,'source:'+row.id,row.id,b.version));}
statements.push(db().prepare('UPDATE entities SET data=?,deleted=?,version=version+1,updated=? WHERE id=? AND version=?').bind(JSON.stringify(data),deleted,now,b.id,b.version));const result=await db().batch(statements);if(!result.at(-1)!.meta.changes)throw new HttpError(409,'This item changed. Reload before saving');return Response.json(visible(await entity(b.id,u.userId),u.userId));}catch(e){return responseError(e);}}
