export const tasks=[{id:'all',label:'Any next step',primary:[],companions:[]},{id:'beginner',label:'I am learning to drive for the first time',primary:['driving-beginner-2026'],companions:['driving-licence']},{id:'experienced',label:'I want an experienced driver’s test account',primary:['driving-golden-2025'],companions:['driving-licence']},{id:'saadiyat',label:'I am comparing one-bedroom homes on Saadiyat',primary:['housing-saadiyat-grace'],companions:['verify-tenancy','utilities-support']},{id:'tenancy',label:'I have a tenancy document to check',primary:['verify-tenancy'],companions:['utilities-support']},{id:'founder-community',label:'I want to explore founder communities',primary:['founder-khalid'],companions:[]},{id:'business',label:'I am planning business registration',primary:['business-setup'],companions:[]},{id:'schools',label:'I am preparing school questions',primary:['school-admissions','school-fees'],companions:['family-swiss-expat']},{id:'campus',label:'I am exploring campus life',primary:['student-brettany'],companions:['student-residency']},{id:'community',label:'I want to build local connections',primary:['linkedin-alicia-parra'],companions:[]}] as const;
export const applicability:Record<string,{why:string;mismatch:string;companions:string[]}>={
'driving-beginner-2026':{why:'First-time driver and regular training are explicit in the account.',mismatch:'This does not establish Golden Chance or foreign-licence exchange eligibility.',companions:['driving-licence']},
'driving-golden-2025':{why:'The author already had driving experience and added practice for confidence.',mismatch:'This is not a beginner’s route or an individual eligibility decision.',companions:['driving-licence']},
'housing-saadiyat-grace':{why:'The named area and one-bedroom home match this specific setting.',mismatch:'One household tour does not compare districts; no rent amount was observed.',companions:['verify-tenancy','utilities-support']},
'housing-hunt-baxter':{why:'Documents restarting a search after missing out on a first choice.',mismatch:'No particular neighbourhood or available listing is established.',companions:['verify-tenancy','utilities-support']},
'verify-tenancy':{why:'An official verification action for someone who already has a contract number.',mismatch:'Not a listing comparison, legal review or fraud guarantee.',companions:[]},
'founder-khalid':{why:'The interview concerns product building, hackathons and the 42 talent community.',mismatch:'Not a licensing guide or independent proof of commercial outcomes.',companions:['business-setup']},
'business-setup':{why:'Official registration planning starts with activity, legal form and approvals.',mismatch:'Requirements vary; founder networking does not establish licensing eligibility.',companions:[]},
'student-brettany':{why:'Residence halls, meals, classes and friendships in a named campus setting.',mismatch:'University-hosted framing; not independent or about off-campus renting.',companions:['student-residency']},
'family-swiss-expat':{why:'Connects scouting and school visits with one family’s adjustment.',mismatch:'Historical publisher interview; no named-school comparison or current fees.',companions:['school-admissions','school-fees']},
'linkedin-alicia-parra':{why:'Addresses wanting community after choosing a longer-term base.',mismatch:'No verified visa route, affordability finding or job offer.',companions:[]},
'career-christine':{why:'Connects job adaptation, commuting and first-month expenses.',mismatch:'Commercial recruiter-hosted testimonial; benefits are employer-specific.',companions:['employment-process','work-residency']}
};
export function relevanceGroup(sourceId:string,taskId:string){const task=tasks.find(t=>t.id===taskId);if(!task||task.id==='all')return 2;if((task.primary as readonly string[]).includes(sourceId))return 0;if((task.companions as readonly string[]).includes(sourceId))return 1;return 2;}
