import { newDiscovery } from './new-discovery';
import { applicability } from './applicability';
const checked='2026-10-02';
function official(id:string,title:string,creator:string,topic:string,url:string,summary:string,caveat:string,verification='Official page text inspected'){return {id,owner:'editorial',kind:'source',data:{title,creator,topic,url,summary,caveat,verification,type:'official guidance',published:null,checked,sponsorship:'Not assessed',status:'available',platform:'Official source',permission:'Short original editorial summary; original source linked',claims:[{text:summary,basis:'official guidance',citation:id}]}};}
function experience(id:string,title:string,creator:string,platform:string,topic:string,url:string,published:string|null,summary:string,caveat:string,depth='Original public text inspected'){return {id,owner:'editorial',kind:'source',data:{title,creator,platform,topic,url,published,summary,caveat,checked,type:'personal experience',sponsorship:platform==='SA-Recruitment'?'Recruiter-hosted promotional testimonial':'Not assessed',status:'available',verification:depth,permission:'Link-out only; no media, full-text copying or partnership established',claims:[{text:summary,basis:'personal experience',citation:id}]}};}
const seed=[
official('driving-licence','Driver and vehicle licensing','Abu Dhabi Mobility','Driving','https://admobility.gov.ae/en/driver-licensing-services','The official starting point for learning to drive, licence renewal and eligible foreign-licence exchanges.','Exchange is conditional. Check the specific TAMM service, UAE Pass and active traffic-file requirements.'),
official('hafilat','Getting around with Hafilat','Abu Dhabi Mobility','Everyday life','https://admobility.gov.ae/en/pb-bus-service/hafilat-cards','Learn how the Hafilat card is used and where to buy or recharge it.','Products, fares and coverage can change. This is not live route or fare information.'),
official('accessible-transport','Accessible transport support','Abu Dhabi Mobility','Everyday life','https://admobility.gov.ae/People-of-Determination','Check transport support, adapted vehicles and application requirements described by the mobility authority.','Benefits are conditional. Confirm applicable cards, bookings and availability.'),
official('school-admissions','Prepare your school admissions questions','ADEK','Schools & family','https://www.adek.gov.ae/-/media/Project/TAMM/ADEK/Policies/School-Policies/Teaching-and-Learning/ADEK_S_Student-Administrative-Affairs-Policy_EN_1_2.pdf','Schools must make admissions policies available and explain procedures, timelines and required documents.','Policy September 2025 v1.2. Seats, placement and individual circumstances need confirmation.','Official PDF inspected; relevant evidence page 5'),
official('school-fees','Understand a school fee schedule','ADEK','Schools & family','https://adek.gov.ae/-/media/Project/TAMM/ADEK/Policies/School-Policies/Governance-and-Operations/ADEK_S_Fees-Policy_EN.pdf','School charges may include tuition, learning resources, uniforms, transport and extracurricular activities.','Policy September 2024 v1.1. Obtain current approved fees and refund terms from your chosen school.','Official PDF inspected; relevant evidence page 3'),
official('inclusive-education','Explore learning support','ADEK','Schools & family','https://adek.gov.ae/Education-of-People-of-Determination','Explore mainstream inclusion support and routes to in-school therapeutic services.','Support has different eligibility criteria; some specialized provision is for eligible Emirati students. No universal funding guarantee.'),
official('verify-tenancy','Check a tenancy document','ADREC','Housing','https://adrec.gov.ae/en/verify-document','ADREC provides an official document-verification tool, including tenancy-contract checks.','Verification is not a legal review or property inspection. Enter contract details only on the official service.'),
official('utilities-support','Moving and utility support','TAQA Distribution','Housing','https://taqadistribution.com/addc/en-us/residential/help-and-support/customer-care','Find the provider’s navigation for moving, billing and service requests.','No deposits, activation times or automatic connection were verified. Confirm requirements for your premises.','Limited verification: official search-index text; direct extraction empty'),
official('work-residency','Employment and residency routes','UAE Government','Jobs & opportunities','https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/residence-visa-for-working-in-the-uae','Compare the official overview of employment-residency routes and who handles applications.','National orientation only. Confirm route and issuing authority with the employer.','Limited verification: official indexed text; direct extraction empty'),
official('student-residency','Student residency starting points','UAE Government','Schools & family','https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/residence-visa-for-studying-in-the-uae','Read the overview of parent or accredited-institution sponsorship for student residency.','Admission alone does not establish residency approval. Researchers observed differing indexed update dates; publication remains unknown.','Limited verification: official indexed text; direct extraction empty'),
official('business-setup','Plan your business setup sequence','ADDED','Jobs & opportunities','https://www.added.gov.ae/en/set-up/establish-your-business','Begin with business activity and legal form, then identify licensing steps and any additional approvals.','Requirements vary by activity, location, ownership and route. No fixed cost or instant licensing promise. Source updated 2026-09-24.'),
official('employment-process','From job offer to work permission','UAE Government','Jobs & opportunities','https://u.ae/information-and-services/jobs/employment-in-the-private-sector/job-offers-and-work-permits-and-contracts/expatriates-employment-in-private-sector','The government describes offer, contract, work permit and work visa as employment-process stages.','Private-sector overview. Free zones and other employment arrangements may differ. An offer does not itself permit work.','Limited verification: official indexed text'),
experience('housing-saadiyat-grace','A one-bedroom home on Saadiyat Island','Lottie Grace','YouTube','Housing','https://www.youtube.com/watch?v=kQox4XkIYwA','2026-06-28','A home tour with one household’s reasons for choosing Saadiyat and a discussion of annual rent.','The observed description does not give the rent amount. This is one household’s perspective.','Description-only review; playback and embed permission unverified'),
experience('food-week-grace','A week of groceries and eating out','Lottie Grace','YouTube','Everyday life','https://www.youtube.com/watch?v=zodFLhLH9xE','2026-07-12','One couple’s week of groceries, delivery, food at work and eating out.','No total was present in the reviewed description. Their choices do not represent all residents.','Description-only review; playback and embed permission unverified'),
experience('housing-hunt-baxter','Apartment hunting after a first choice falls through','Hannah Baxter','YouTube','Housing','https://www.youtube.com/watch?v=b6TLnryHvoI','2023-12-20','A renewed apartment search after missing out on the first choice.','Neighbourhoods, prices, terms and the eventual choice are unknown from the description.','Description-only review; playback and embed permission unverified'),
experience('driving-assylbekova','One licence journey in Abu Dhabi','Aidana Assylbekova','YouTube','Driving','https://www.youtube.com/watch?v=h4tjg-xZqBU','2021-09-11','A historical account of eye test, translation, theory and driving tests.','Historical 2021 experience, not current requirements or fees.','Description-only review; playback and embed permission unverified'),
experience('driving-beginner-2026','A beginner’s driving-licence journey','Confident_Staff_2475','Reddit','Driving','https://www.reddit.com/r/abudhabi/comments/1qcpta2/how_i_got_my_abu_dhabi_driving_license/','2026-01-14','A first-time driver recounts training, scheduling and nerves on test day.','The author’s post and later comments differ on package labels and price. Preserve that contradiction; use official requirements separately.'),
experience('driving-golden-2025','A Golden Chance applicant’s experience','Head-Ad4793','Reddit','Driving','https://www.reddit.com/r/abudhabi/comments/1kq8du4/abu_dhabi_driving_license_experience_2025_golden/','2025-05-19','An experienced driver describes theory, simulator booking, additional practice and the road test.','Different from a complete beginner’s route. Personal timing and fees are not current rules.'),
experience('family-swiss-expat','A family’s scouting trip and adjustment','Swiss Family Expat; writer Nelly Jacques','Expat.com','Schools & family','https://www.expat.com/en/expat-mag/7090-swiss-expat-talks-about-her-move-to-abu-dhabi-with-her-family.html','2022-06-24','A publisher interview about school visits, routines and distance from friends and relatives.','Publisher-hosted interview; no named-school review or current fee confirmation.'),
experience('family-amy-expat','A historical family-life reflection','Amy; writer Veedushi Bissessur','Expat.com','Schools & family','https://www.expat.com/en/expat-mag/664-interview-of-a-british-expat-mom-in-abu-dhabi-united-arab-emirates.html','2016-10-19','A mother describes family routines and practical adjustment in a suburban home.','Historical 2016 perspective. Avoid applying dated cultural, school or housing claims today.'),
experience('student-brettany','A senior’s campus-life perspective','Brettany Gamutea; writer Olivia Richter','MEET NYU','Schools & family','https://meet.nyu.edu/life/a-seniors-inside-look-at-student-life-at-nyu-abu-dhabi/','2026-04-16','A senior shares residence-hall, meal, class and friendship experiences at NYU Abu Dhabi.','University-hosted marketing communications; campus-specific, not independent evidence about other universities.'),
experience('student-aathma','A historical day at NYU Abu Dhabi','Aathma Dious','NYU Abu Dhabi','Schools & family','https://nyuad.nyu.edu/en/news/latest-news/community-life/2017/november/no-day-at-nyuad-is-quite-the-same.html','2017-11-16','A student-authored photo diary of classes, dining and study spaces.','Historical 2017 university-hosted account. Facilities or services are not current entitlements.'),
experience('career-christine','A teacher’s first month abroad','Christine; SA-Recruitment','SA-Recruitment','Jobs & opportunities','https://www.sa-recruitment.com/post/from-south-africa-to-the-middle-east-my-first-hand-experience-as-a-south-african-teacher-in-abu-dha','2025-03-12','A teacher describes classroom technology, commuting, early expenses and adjusting to work abroad.','Commercial recruiter-hosted testimonial. Benefits are employer-specific; promotional ending.'),
experience('founder-khalid','Learning by building in Abu Dhabi','Muhammed Khalid; writer Ouiam Akchar','42 The Network','Jobs & opportunities','https://www.42network.org/blog/whos-behind-42-muhammed-khaled-founder-ceo-of-airev/','2026-05-28','A founder discusses building products and engaging with local talent through hackathons.','Education-network partner interview; not a business-setup guide or independent assessment.'),
experience('linkedin-anthony-sassine','Moving a family from the US to Abu Dhabi','Anthony Sassine, CFA','LinkedIn','Jobs & opportunities','https://www.linkedin.com/posts/anthony-sassine-cfa-19671518_thank-you-all-for-the-lovely-wishes-last-activity-7234435516639641600-q-Sa',null,'A firsthand relocation announcement about a family move and a professional chapter in the region.','Only relative date observed. No school, rental cost, paperwork checklist or long-term outcome established.'),
experience('linkedin-kris-watson','Finding your feet in a teaching role','Kris Watson','LinkedIn','Everyday life','https://www.linkedin.com/posts/kris-watson-a67518293_just-over-a-week-ago-i-moved-to-abu-dhabi-activity-7496788519550599168-ZduM',null,'An early-arrival reflection about a school commute, coffee spots and colleagues.','Exact publication date unknown. Positive early reflection is not a long-term school review or rent evidence.'),
experience('linkedin-alicia-parra','Choosing a base after working remotely abroad','Alicia Parra','LinkedIn','Everyday life','https://www.linkedin.com/posts/aliciaparra_after-5-years-of-working-remotely-from-different-activity-7498981211470454784-X2n5',null,'A personal reflection on wanting community and stability after living in several countries.','Relative dates differed between retrievals. Views on opportunity are personal; no visa route, cost breakdown or job offer verified.')
];
export const catalogue=[...seed,...newDiscovery].map(s=>({...s,data:{...s.data,...(s.data.platform==='YouTube'?{nativeEmbedApproved:true,permission:'Provider-hosted YouTube embed under native publisher controls. Original content is not copied; provider may restrict playback.'}:{}),applicability:applicability[s.id]??null}}));
export const challenges=[{id:'sample-neighbourhood',title:'Make a newcomer neighbourhood comparison',requirements:['Cite two public sources','Separate facts and assumptions','Explain a decision tradeoff'],label:'Illustrative challenge · no employer or endorsement'},{id:'sample-service',title:'Improve a newcomer service journey',requirements:['Document a user problem','Create a bounded prototype','Explain your actual contribution'],label:'Illustrative challenge · no production work required'}];
