import { z } from 'zod';
const s=z.string().trim().max(6000); const short=z.string().trim().max(300); const list=z.array(short).max(100).default([]); const optional=short.default('');
export const kinds=['profile','goal','collection','scenario','proof','request','helper','submission','lesson','source'] as const;
export type Kind=typeof kinds[number];
const url=z.string().url().max(2000).refine(v=>{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&!/^(localhost|127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.|\[|0\.)/i.test(u.hostname)&&u.hostname.includes('.')},'Use an HTTPS source URL');
const action=z.object({id:short,title:short,owner:short.default('Me'),status:z.enum(['todo','doing','done']).default('todo'),dependsOn:list,evidence:optional});
export const schemas={
profile:z.object({name:optional,goals:list,circumstances:s.default(''),interests:list,language:optional,roles:list,constraints:s.default('')}),
goal:z.object({title:short.min(1),outcome:s.default(''),deadline:optional,evidence:list,choices:s.default(''),agreedChoices:list,unresolvedChoices:list,blockers:list,unknowns:list,actions:z.array(action).max(100).default([]),nextStep:optional,criteria:s.default(''),privateNotes:s.default(''),confirmed:z.boolean().default(false),confirmationEvidence:s.default(''),draft:s.default('')}),
collection:z.object({title:short.min(1),sources:list,notes:s.default(''),privateNotes:s.default('')}),
scenario:z.object({title:short.min(1),startingCash:z.number().finite().nonnegative().nullable().default(null),income:z.number().finite().nonnegative().nullable().default(null),items:z.array(z.object({id:short,label:short,cash:z.number().finite().nonnegative().nullable(),hours:z.number().finite().nonnegative().nullable(),basis:z.enum(['user fact','assumption','official guidance','personal experience']),sourceId:optional,dependsOn:list})).max(100).default([]),budget:z.number().finite().nonnegative().nullable().default(null),availableHours:z.number().finite().nonnegative().nullable().default(null),constraints:s.default(''),rules:z.array(z.object({id:short,label:short,type:z.enum(['max cash','max hours','require evidence']),limit:z.number().finite().nonnegative().nullable(),itemId:optional})).max(50).default([])}),
proof:z.object({title:short.min(1),challenge:optional,skills:list,requirements:list,requirementMap:z.array(z.object({requirement:short,evidence:s,status:z.enum(['unknown','met','partial','gap'])})).max(100).default([]),artifact:s.default(''),contribution:s.default(''),gaps:list,review:z.enum(['not requested','requested','reviewed']).default('not requested'),reviewer:optional,reviewEvidence:s.default(''),reviewHash:optional,privateNotes:s.default('')}),
request:z.object({title:short.min(1),question:s.min(1),context:s.default(''),topic:optional,status:z.enum(['draft','open','accepted','answered','resolved']).default('draft'),helperId:optional,replies:z.array(z.object({author:short,text:s,at:short})).max(100).default([]),resolution:s.default(''),feedback:optional}),
helper:z.object({name:short.min(1),topics:list,about:s.default(''),availability:optional,optIn:z.boolean().default(false)}),
submission:z.object({title:short.min(1),url,creator:short.min(1),topic:short,permission:s.default(''),attribution:s.default(''),sponsorship:optional,note:s.default(''),status:z.enum(['pending','approved','rejected','withdrawn','correction']).default('pending'),reason:s.default('')}),
lesson:z.object({title:short.min(1),experience:s.min(1),circumstances:s.default(''),sourceIds:list,consent:z.boolean().default(false)}),
source:z.object({title:short.min(1),url,creator:short,topic:short,summary:s,type:z.enum(['official guidance','personal experience']),published:short.nullable().default(null),checked:optional,sponsorship:optional,status:z.enum(['available','broken','withdrawn','needs review']).default('available'),contradictions:s.default(''),permission:s.default(''),platform:optional,nativeEmbedApproved:z.boolean().default(false),applicability:z.object({why:s,mismatch:s,companions:list}).nullable().default(null),caveat:s.default(''),verification:s.default(''),claims:z.array(z.object({text:s,basis:z.enum(['official guidance','personal experience','assumption','user fact']),citation:short})).default([])})};
export function validate(kind:Kind,data:unknown){const parsed=schemas[kind].parse(data);if(kind==='goal'){const g=parsed as z.infer<typeof schemas.goal>;if(g.confirmed&&!g.confirmationEvidence.trim())throw new Error('Add evidence before confirming an outcome');const ids=new Set(g.actions.map(a=>a.id));if(ids.size!==g.actions.length)throw new Error('Duplicate action IDs');for(const a of g.actions){if(a.dependsOn.some(d=>!ids.has(d)||d===a.id))throw new Error('Invalid prerequisite');if(a.status==='done'&&a.dependsOn.some(d=>g.actions.find(x=>x.id===d)?.status!=='done'))throw new Error('Complete prerequisites first');}const visiting=new Set<string>(),done=new Set<string>();function visit(id:string){if(visiting.has(id))throw new Error('Actions contain a dependency cycle');if(done.has(id))return;visiting.add(id);for(const d of g.actions.find(x=>x.id===id)!.dependsOn)visit(d);visiting.delete(id);done.add(id);}for(const id of ids)visit(id);}if(kind==='scenario'){const p=parsed as z.infer<typeof schemas.scenario>;const ids=new Set(p.items.map(i=>i.id));if(ids.size!==p.items.length)throw new Error('Duplicate scenario item IDs');const visiting=new Set<string>(),done=new Set<string>();function visit(id:string){if(visiting.has(id))throw new Error('Scenario prerequisites contain a cycle');if(done.has(id))return;visiting.add(id);for(const d of p.items.find(i=>i.id===id)!.dependsOn){if(ids.has(d))visit(d);}visiting.delete(id);done.add(id);}for(const id of ids)visit(id);if(new Set(p.rules.map(r=>r.id)).size!==p.rules.length)throw new Error('Duplicate constraint IDs');}if(kind==='proof'){const p=parsed as z.infer<typeof schemas.proof>;if(p.review==='reviewed'&&(!p.reviewer||!p.reviewEvidence))throw new Error('Human review needs reviewer and evidence');}return parsed;}
export function summarizeScenario(data:z.infer<typeof schemas.scenario>){const cashKnown=data.items.every(i=>i.cash!==null),timeKnown=data.items.every(i=>i.hours!==null);const ruleConflicts:string[]=[];for(const r of data.rules??[]){const items=r.itemId?data.items.filter(i=>i.id===r.itemId):data.items;if(!items.length){ruleConflicts.push(`${r.label}: target item is missing`);continue;}if(r.type==='require evidence'){if(items.some(i=>!i.sourceId))ruleConflicts.push(`${r.label}: supporting evidence has not been supplied`);}else{const values=items.map(i=>r.type==='max cash'?i.cash:i.hours);if(r.limit===null||values.some(v=>v===null))ruleConflicts.push(`${r.label}: unknown inputs need confirmation`);else if(values.reduce<number>((a,v)=>a+(v??0),0)>r.limit)ruleConflicts.push(`${r.label}: exceeds your ${r.type==='max cash'?'cash':'time'} constraint`);}}const cash=data.items.reduce((a,i)=>a+(i.cash??0),0),hours=data.items.reduce((a,i)=>a+(i.hours??0),0);return {cash:cashKnown?cash:null,hours:timeKnown?hours:null,knownCash:cash,knownHours:hours,cashRemaining:cashKnown&&data.startingCash!==null&&data.income!==null?Math.round((data.startingCash+data.income-cash)*100)/100:null,hoursRemaining:timeKnown&&data.availableHours!==null?data.availableHours-hours:null,conflicts:[...ruleConflicts,...(data.budget!==null&&cash>data.budget?['Known costs exceed your budget']:[]),...(data.availableHours!==null&&hours>data.availableHours?['Known time exceeds your available hours']:[]),...data.items.filter(i=>i.dependsOn.some(id=>!data.items.some(x=>x.id===id))).map(i=>`Missing prerequisite for ${i.label}`)],unknowns:data.items.filter(i=>i.cash===null||i.hours===null).map(i=>i.label)};}
export type Entity={id:string;owner:string;kind:Kind;data:Record<string,any>;version:number;deleted:number;created:string;updated:string;role?:string};
