/** Reviewed original links supplied by source research. No media copied. */
const publisher='Experience Abu Dhabi / Department of Culture and Tourism';
const officialRows=[
['getting-around','Compare ways to get around','plan-your-trip/getting-around-abu-dhabi','Everyday life','An orientation hub for taxis, buses, bike sharing and rentals, with links to individual transport options.','Verify current fares, payment methods, routes and accessibility with the operator. Tourism pages contain inconsistent payment details.'],
['accessible-travel','Plan an accessible outing','plan-your-trip/accessible-abu-dhabi/accessible-holidays','Everyday life','A starting point for airport assistance and accessible transport, accommodation and attractions.','Confirm suitability, eligibility, documents and reservation requirements with the provider.'],
['culture-traditions','Get to know local culture','plan-your-trip/culture-and-traditions','Everyday life','An introduction to Emirati arts, food, heritage and traditional sports, with onward links to cultural venues.','A broad tourism introduction, not an exhaustive etiquette guide or statement of law.'],
['packing-practical','Feel ready for your first week','plan-your-trip/essential-info/what-to-pack-for-your-abu-dhabi-trip/','Everyday life','Prepare for outdoor heat, cool interiors and venue-specific clothing expectations.','Seasonal guidance is not a forecast. Clothing recommendations should not be restated as laws.'],
['al-gurm','Take a mangrove-side walk','where-to-go/beaches/al-gurm-corniche','Everyday life','Explore a mangrove-side promenade for walking, cycling and relaxed time outside.','Check weather, temporary closures and separate business or activity charges.'],
['umm-al-emarat','Find a family park','things-to-do/nature-and-wildlife/parks/umm-al-emarat-park','Schools & family','Discover an Al Mushrif park with gardens, a lawn and family facilities, with a link to its own booking site.','Confirm current admission prices, opening hours, events and food rules with the park.'],
['local-cuisine','Explore markets and local food','plan-your-trip/culture-and-traditions/local-cuisine','Everyday life','An introduction to shared dining traditions, Mina Market and ingredients used in Emirati cooking.','Market hours, prices, transport and individual accessibility are not established here.'],
['emirati-dishes','Try your first Emirati meal','plan-your-trip/article-hub/emirati-cuisine-the-dishes-to-try-and-where-to-try-them','Everyday life','Recognise local meals, sweets, dates and coffee, with places to try them.','Confirm menus, ingredients, allergies and dietary requirements with the venue.'],
['al-ain','Meet Al Ain','where-to-go/regions/al-ain','Everyday life','Meet the emirate’s inland city through its oases, historic sites and mountain landscape.','A visitor overview, not evidence about housing costs, schools or relocation suitability.'],
['al-ain-oasis','Walk through an oasis','things-to-do/nature-and-wildlife/natural-wonders/al-ain-oasis','Schools & family','Explore palm-shaded paths, traditional irrigation and educational stops at Al Ain Oasis.','Check hours, rental availability, prices and specific accessibility needs with the venue.'],
['qasr-al-hosn','Start with Abu Dhabi’s story','things-to-do/culture/heritage/qasr-al-hosn','Everyday life','Connect the historic fort to crafts, Arabic coffee, the Cultural Foundation and the children’s library.','Check individual venue hours, workshops, ticket inclusions and access. Festival descriptions do not establish future dates.'],
['business-etiquette','Prepare for local work conversations','abu-dhabi-convention-and-exhibition-bureau/business-culture/local-business-etiquette','Jobs & opportunities','A light introduction to respectful professional interactions and checking mutual understanding.','Written for business events; not employment guidance, a universal description of people or a statement of law.']
];
const instagramRows=[
['concert','Candlelight, music and an evening out','reel/Dd0H19XI3yC/','2026-09-27','Everyday life','Nadia shares her Candlelight concert evening at Emirates Palace, featuring a Hans Zimmer tribute.','Past evening experience. Future dates, booking and current availability are unknown.','Not assessed'],
['murjan','A family afternoon at Murjan Splash Park','reel/DdrSiWMNPhT/','2026-09-24','Schools & family','Nadia shares a family afternoon at Murjan Splash Park inside Khalifa Park, with water slides, a lazy river and bumper boats.','Personal activity account. Current hours, prices and suitability require provider confirmation.','Not assessed'],
['matcha','Nadia’s favourite matcha finds','p/DdqjuQdkRyu/','2026-09-24','Everyday life','A roundup of some of Nadia’s favourite matcha finds around Abu Dhabi.','Individual cafe names and carousel details were not inspected.','Not assessed'],
['rixos','Is a Saadiyat resort day pass worth it?','p/DdjAC6fDWJs/','2026-09-21','Everyday life','Nadia weighs her full-day Rixos Premium Saadiyat Island resort experience against its cost.','Posted price is historical, not a current quote. Inclusions and availability need direct confirmation.','Creator states self-funded and not sponsored'],
['pilates','Pilates and a different kind of afternoon','reel/DdiU0rehFGh/','2026-09-20','Everyday life','A look at Nadia’s Pilates afternoon at Porsche Centre Abu Dhabi.','Past event inspiration. Recurrence and public booking are unknown.','Not assessed'],
['neighbourhood','Choosing a neighbourhood that fits your life','p/DdYf-vVkSoC/','2026-09-17','Housing','Nadia introduces established neighbourhoods and lifestyle, commuting and budget questions to consider when choosing where to live.','Specific carousel neighbourhoods and rents were not inspected. Caption promotes a paid relocation guide.','Commercial promotion: creator’s paid relocation guide'],
['after-dark','Abu Dhabi after dark','reel/DdZOtd4N3of/','2026-09-17','Everyday life','Nadia shares an evening city view and her appreciation for Abu Dhabi.','Exact filming location is unverified.','Not assessed'],
['september','A month of Abu Dhabi discoveries','p/Dd81ibgkZqE/','2026-10-01','Everyday life','Nadia’s collection of favourite Abu Dhabi finds and moments from September.','Individual carousel places were not inspected.','Not assessed']
];
const tiktokRows=[
['umut','An attractions overview for a new arrival','https://www.tiktok.com/@umutdxb/video/7450801276549565703','@umutdxb','An indexed attractions overview covering places including Jubail Mangrove Park, Al Ain Oasis, Louvre Abu Dhabi and Yas Island.','Broad inspiration only. Direct TikTok opens require login or age verification; content and operating details were not independently watched.'],
['abra','An abra ride around Qaryat Al Beri','https://www.tiktok.com/@_explorer__/video/7313088213520764178','@_explorer__','An indexed personal boat-ride experience around Shangri-La Qaryat Al Beri canals.','Historical indexed prices are not current quotes. Direct playback and publication date are unverified.'],
['mosque','A creator’s mosque visit tips','https://www.tiktok.com/@thetraveltauruss/video/7306695655798476062','@thetraveltauruss','Indexed personal visitor guidance about clothing and photography at Sheikh Zayed Grand Mosque.','Check the mosque’s current official visitor guidance. Direct playback and publication date are unverified.']
];
function source(id:string,title:string,url:string,creator:string,topic:string,summary:string,caveat:string,platform:string,type:string,published:string|null,verification:string,sponsorship='Not assessed'){return {id,owner:'editorial',kind:'source',data:{title,url,creator,topic,summary,caveat:id==='tiktok-umut'?'Broad travel inspiration only. Native playback and attribution observed; full video, current opening hours, prices and attraction availability are not audited.':caveat,platform,type,published,checked:'2026-10-02',verification:id==='tiktok-umut'?'Official native player loaded and playback progressed on 2026-10-02. Description observed; full video and current attraction availability not audited.':id==='nadia-september'?'Original public post and provider-generated Embed code inspected on 2026-10-02. Native photo display and carousel interaction tested; individual places and current availability unaudited.':verification,sponsorship,status:'available',nativeEmbedApproved:['Instagram','TikTok'].includes(platform),permission:id==='tiktok-umut'?'Provider-hosted native TikTok player; no copied media. Creator attribution and original links retained.':id==='nadia-september'?'Public post offered provider-generated Embed code. Instagram API Terms explicitly approved by the user on 2026-10-02. Provider-hosted display only; no copied media or automated API.':['Instagram','TikTok'].includes(platform)?'Native provider embed requested by the user. Provider visibility and playback controls apply; no media copied or scraped.':'Original editorial summary and link-out only; no copied media or affiliation',claims:[{text:summary,basis:type,citation:id}],contradictions:id==='visit-getting-around'?'Tourism bus page describes coin payments while the operator describes Hafilat. Use current operator guidance; do not infer current fares.':''}};}
export const newDiscovery=[...officialRows.map(([id,title,path,topic,summary,caveat])=>source('visit-'+id,title,'https://visitabudhabi.ae/en/'+path,publisher,topic,summary,caveat,'Official source','official guidance',null,'Official tourism page read; publication date not visible')),...instagramRows.map(([id,title,path,date,topic,summary,caveat,sponsorship])=>source('nadia-'+id,title,'https://www.instagram.com/abudhabi.finds/'+path,'Nadia · @abudhabi.finds',topic,summary,caveat,'Instagram','personal experience',date,'Original logged-out caption reviewed; date observed in image alt. Playback and embed not tested.',sponsorship)),...tiktokRows.map(([id,title,url,creator,summary,caveat])=>source('tiktok-'+id,title,url,creator,'Everyday life',summary,caveat,'TikTok','personal experience',null,'Limited review: original URL observed through Airial’s linked-post UI. Direct login/age gate; no playback or date verified. Metadata source: https://airial.travel/attractions/united-arab-emirates/abu-dhabi/khalifa-park-abu-dhabi-U6hJWn3W'))];
